[package]
name = "rust-toys"
version = "0.1.0"
authors = ["hyuuko <751533978@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
